# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc048a19c6e37519d0dad1fd145d3134fd67977442debf9121189b4abdb4be54ab9e0c2bfb435fc43b9c657af856586b8f539928bf70fc485e92dd8b97af678a

test:
  secret_key_base: ae124a082c0bfc4ca292c30cef0040233ea129924c027a7552ce0851138a60bd1ebcc56a1d79b2224aac9413b6092ce96fb34b3139d248eb9a6872d474ff3121

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
